language: python
python:
- '3.3'
before_install:
- pip install -r requirements.txt
- git clone https://github.com/zisk/blue-penguin.git
- pelican-themes -i ./blue-penguin
script: pelican -s publishconf.py content 
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  bucket: "blog.reboost.net"
  skip_cleanup: true
  local_dir: output
  
